"""add_review_architecture_tables

Revision ID: c7bd48854156
Revises: d859c6bb84d6
Create Date: 2026-07-06 14:05:34.811847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7bd48854156'
down_revision: Union[str, Sequence[str], None] = 'd859c6bb84d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layer_ranges', 'context_before',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('layer_ranges', 'context_after',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('layers', 'files',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('layers', 'symbol_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('layers', 'risk_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('layers', 'review_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pull_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pull_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_comments', 'is_synced',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('review_jobs', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('review_jobs', 'attempt',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('review_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('review_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'pipeline_failures',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of AI passes that returned error data. 0=clean, 1-2=partial failure with conservative verdict.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('snapshots', 'files_changed',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('snapshots', 'additions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('snapshots', 'deletions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###

    # ── 1. Create review_runs table ──
    op.create_table(
        'review_runs',
        sa.Column('id', postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column('repo', sa.String(length=255), nullable=False),
        sa.Column('pr_number', sa.Integer(), nullable=False),
        sa.Column('mode', sa.String(length=50), nullable=False),
        sa.Column('base_sha', sa.String(length=40), nullable=True),
        sa.Column('head_sha', sa.String(length=40), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
        sa.Column('reviewed_files_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('new_findings_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('duplicate_findings_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('resolved_findings_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('posted_comments_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    )

    # ── 2. Create review_surfaces table ──
    op.create_table(
        'review_surfaces',
        sa.Column('id', postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column('repo', sa.String(length=255), nullable=False),
        sa.Column('pr_number', sa.Integer(), nullable=False),
        sa.Column('surface_type', sa.String(length=50), nullable=False),
        sa.Column('marker', sa.String(length=100), nullable=True),
        sa.Column('github_id', sa.BigInteger(), nullable=True),
        sa.Column('last_updated_sha', sa.String(length=40), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # ── 3. Create findings table ──
    op.create_table(
        'findings',
        sa.Column('id', postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column('repo', sa.String(length=255), nullable=False),
        sa.Column('pr_number', sa.Integer(), nullable=False),
        sa.Column('signature', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('line', sa.Integer(), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('severity', sa.String(length=50), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('evidence', sa.Text(), nullable=True),
        sa.Column('impact', sa.Text(), nullable=True),
        sa.Column('fix', sa.Text(), nullable=True),
        sa.Column('first_seen_sha', sa.String(length=40), nullable=True),
        sa.Column('last_seen_sha', sa.String(length=40), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='new'),
        sa.Column('github_comment_id', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index('idx_findings_repo_pr_sig', 'findings', ['repo', 'pr_number', 'signature'])
    op.create_index('idx_findings_signature', 'findings', ['signature'])

    # ── 4. Create file_review_history table ──
    op.create_table(
        'file_review_history',
        sa.Column('id', postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column('repo', sa.String(length=255), nullable=False),
        sa.Column('pr_number', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('first_seen_sha', sa.String(length=40), nullable=True),
        sa.Column('last_seen_sha', sa.String(length=40), nullable=True),
        sa.Column('review_status', sa.String(length=100), nullable=False),
        sa.Column('findings_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('skipped_reason', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint('repo', 'pr_number', 'file_path', name='uq_file_review_history_repo_pr_file'),
    )
    op.create_index('idx_file_review_history_repo_pr', 'file_review_history', ['repo', 'pr_number'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('snapshots', 'deletions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('snapshots', 'additions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('snapshots', 'files_changed',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('reviews', 'pipeline_failures',
               existing_type=sa.INTEGER(),
               comment='Number of AI passes that returned error data. 0=clean, 1-2=partial failure with conservative verdict.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('review_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('review_jobs', 'attempt',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('review_jobs', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('review_comments', 'is_synced',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pull_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pull_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('layers', 'review_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('layers', 'risk_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('layers', 'symbol_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('layers', 'files',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('layer_ranges', 'context_after',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('layer_ranges', 'context_before',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    # ### end Alembic commands ###
    op.drop_index('idx_file_review_history_repo_pr', table_name='file_review_history')
    op.drop_table('file_review_history')
    op.drop_index('idx_findings_signature', table_name='findings')
    op.drop_index('idx_findings_repo_pr_sig', table_name='findings')
    op.drop_table('findings')
    op.drop_table('review_surfaces')
    op.drop_table('review_runs')
